services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_WEB3FORMS_ACCESS_KEY: ${VITE_WEB3FORMS_ACCESS_KEY}
    container_name: savitron-web
    ports:
      - "2252:80"
    restart: unless-stopped
